DROP DATABASE IF EXISTS db_translate;

CREATE DATABASE db_translate;

use db_translate;

CREATE TABLE words(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    word VARCHAR(20) NOT NULL ,
    translated VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

DESCRIBE words;